name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
        working-directory: ./app  # appディレクトリ内で実行
      - name: Build
        run: npm run build
        working-directory: ./app  # appディレクトリ内で実行
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./app/public  # appディレクトリ内のpublicをアップロード

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./app/public  # appディレクトリ内にダウンロード
      # - name: Install Firebase CLI
      #   run: npm install -g firebase-tools
      #   working-directory: ./app  # appディレクトリ内で実行
      # - name: Deploy to Firebase
      #   run: firebase deploy
      #   working-directory: ./app  # appディレクトリ内で実行
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
